// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Account struct {
	ID        int64     `json:"id"`
	Username  string    `json:"username"`
	LineID    string    `json:"line_id"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
}
